php-sonic:
  image: php:7.4-apache
  container_name: cont-php
  ports:
    - "8081:80"
    - "443:443"
  volumes:
    - /home/ereck/Documentos/sonic-js:/var/www/html
  links: 
    - db-sonic

